FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

EXPOSE 3090

ENV PORT 3090
ENV WATCHPACK_POLLING true

# Run in development mode with hot reload
CMD ["npm", "run", "dev"]
